export const promise = {
  PENDING: '_PENDING',
  REJECTED: '_REJECTED',
  FULFILLED: '_FULFILLED',
};

export const building = {
  GET_BUILDING_DATA: 'GET_BUILDING_DATA',
};

export const notification = {
  SET_NEW_NOTIFICATION: 'SET_NEW_NOTIFICATION',
  UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
};

export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
